tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/server.crt
        keyFile: /etc/traefik/certs/server.key
  certificates:
    - certFile: /etc/traefik/certs/c2.gla1v3.local.crt
      keyFile: /etc/traefik/certs/c2.gla1v3.local.key
      stores:
        - default
    - certFile: /etc/traefik/certs/server.crt
      keyFile: /etc/traefik/certs/server.key
      stores:
        - default
  options:
    default: {}
    mtls-required:
      clientAuth:
        caFiles:
          - /etc/traefik/certs/ca.crt
        clientAuthType: RequireAndVerifyClientCert

tcp:
  routers:
    c2:
      entryPoints:
        - c2
      rule: "HostSNI(`c2.gla1v3.local`)"
      service: c2
      tls:
        passthrough: true
        options: mtls-required
  services:
    c2:
      loadBalancer:
        servers:
          - address: backend:3001