filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/ossec/logs/alerts/alerts.json
  json.keys_under_root: true
  json.add_error_key: true

setup.template.name: "wazuh"
setup.template.pattern: "wazuh-*"
setup.template.overwrite: true

# Disable setup actions that may call Elasticsearch-specific APIs
setup.ilm.enabled: false
setup.kibana.enabled: false
setup.dashboards.enabled: false
setup.template.enabled: false
setup.license.enabled: false

output.elasticsearch:
  # Send to the local license-proxy which will forward to the real indexer
  hosts: ["http://license-proxy:9200"]
  protocol: "http"
  # Filebeat will talk to the proxy over plain HTTP; the proxy does mTLS to the indexer.
  # Keep allow_older_versions in case Filebeat still performs a version check on connect.
  allow_older_versions: true

# minimal logging
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
